dist: xenial

language: python

python:
  - "3.6"
  - "3.7"

before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
  - sudo apt-get update

install:
  - pip install .
  - pip install -r requirements.txt

script:
  - py.test --cov=./ --cov-config=.coveragerc

after_success:
  - coveralls
